CREATE TABLE products
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id  BIGINT UNIQUE,            -- famme.no product id; NULL for manually added products
    title        VARCHAR(512) NOT NULL,
    vendor       VARCHAR(255),
    product_type VARCHAR(255),
    handle       VARCHAR(512),
    image_url    VARCHAR(1000)
);
