CREATE TABLE product_variants
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id BIGINT,                   -- famme.no variant id; NULL for manually added variants
    product_id  BIGINT        NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    title       VARCHAR(255),
    sku         VARCHAR(255),
    price       NUMERIC(10, 2),
    available   BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_product_variants_product_id ON product_variants (product_id);
